name: Run ShellCheck

on:
  push:
  schedule:
    - cron: '1 5 * * 5'  # UTC
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Max. 79 characters per line
        run: |
          wc -L * | sort -nr
          MLL=$(gawk '{ if(length > L) { L=length } } END { print L }' *)
          (( ${MLL:-80} <= 79 )) || exit 1
